project:
  type: website
  output-dir: docs  


website:
  title: "Guillermo Barrios"
  navbar:
    left:
      # - href: index.qmd
      #   text: Acerca de
      - articulos.qmd
      - text: "Estudiantes"
        menu:
        - href: estudiantes_graduades.qmd
          text: "Studs graduades"
        - href: estudiantes_proceso.qmd
          text: "Studs en proceso"
      - href: cursos.qmd
        text: "Cursos"
      # - href: repositorios.qmd
      #   text: "Repositorios"
      - text: "CV"
        href: https://altamarmx.github.io/cv_quarto/
      
format:
  html:
    theme:
      light: lux
      dark: slate

    include-in-header:
      - text: |
          <script src="https://kit.fontawesome.com/TU_KIT.js" crossorigin="anonymous"></script>

    # css: styles.css
    toc: true

lang: es
